# Generated by Django 5.2.8 on 2025-11-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_emergency",
                    models.BooleanField(
                        default=False, verbose_name="¿Modo Emergencia Activado?"
                    ),
                ),
                (
                    "emergency_message",
                    models.TextField(
                        blank=True,
                        default="Estamos experimentando una falla masiva en el sector. Nuestros técnicos ya están informados y trabajando para solucionarlo. Agradecemos su paciencia.",
                        null=True,
                        verbose_name="Mensaje de Emergencia",
                    ),
                ),
            ],
        ),
    ]
