# Generated by Django 5.2.8 on 2025-11-18 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homeApp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SystemState",
        ),
    ]
