# Generated by Django 5.2.8 on 2025-11-17 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tecnicos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tecnico",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perfil_tecnico",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario (Login)",
            ),
        ),
    ]
