# Generated by Django 5.1.2 on 2025-11-11 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tecnicos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre Cliente"),
                ),
                (
                    "direccion",
                    models.CharField(max_length=255, verbose_name="Dirección física"),
                ),
                (
                    "telefono",
                    models.CharField(max_length=20, verbose_name="Teléfono/WhatsApp"),
                ),
                (
                    "correo",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Correo electrónico (opcional)",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrdenTrabajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Detalle de la falla o servicio"),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("ALTA", "Alta"),
                            ("MEDIA", "Media"),
                            ("BAJA", "Baja"),
                        ],
                        default="MEDIA",
                        max_length=10,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Asignación"),
                            ("ASIGNADA", "Asignada a Técnico"),
                            ("EN_CAMINO", "Técnico en Camino"),
                            ("EN_PROCESO", "En Proceso"),
                            ("TERMINADO", "Trabajo Terminado"),
                            ("CERRADA", "Cerrada por Administración"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "ubicacion_servicio",
                    models.CharField(
                        help_text="Coordenadas lat,long del servicio",
                        max_length=100,
                        verbose_name="Ubicación del Servicio",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "evidencia_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="Link a evidencia (foto/doc)",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones finales"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordenes",
                        to="ordenes.cliente",
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordenes_asignadas",
                        to="tecnicos.tecnico",
                        verbose_name="Técnico asignado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Trabajo",
                "verbose_name_plural": "Órdenes de Trabajo",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
