# Generated by Django 5.2.8 on 2025-11-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordenes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="chat_state",
            field=models.CharField(
                blank=True,
                default="START",
                max_length=50,
                null=True,
                verbose_name="Estado del Chat",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="temp_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                null=True,
                verbose_name="Datos Temporales del Chat",
            ),
        ),
    ]
